sudo: required
dist: xenial

services:
  - xvfb

addons:
  chrome: stable
  firefox: latest

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

language: node_js
node_js:
  - 12
  - 14

cache:
  - node_modules

before_install:
  - export DISPLAY=:99.0
install:
  - npm install
script:
  - npm run test:react
env:
  global:
    - secure: bih8+ZBKGTdIDJ8QFu12KGj9WptznKY0kvDx7nWyarD9Q7ZxDanMnWlmmPNFLk+iHoBzsgdiWnEecxNj5LyJMkxrVDtu02IhufUM6lMUPv4NRCBvoSvQ5YNKXpDhmIxIbkAGFmnyGuTR2srf100fL0Wt9tgVZ78P5BdehAQlfQfKJbPME7Sye+k10+0l/s+22cf3Tlyp4SvkpgU6Tv3E4psZFrNc0aOFS1z/kVTo2oxrUWgDbo53LnpgFhEG66ufViWobmM7Sc1LDYDmZ+62CkEXw/ggwHnXDh5m74MsHc4og+V2PRpzDlM4xZI6RY6dhS+W4UZXmaxGRxiY17FWRL2nas8RvpYRtez3Zd/z36wqvHPfOOp/kC17qiT7OWG0nZlQ9NcmeaJq+pCj9wqCDk+0bAEqisn6s0cmu/rOEb46qpNX/DBUHvoBGvh87LAgoZ3PvdSm4XHOeXgEwoLUB33xY0ltCG95roaJYq5i71yiyh4ZRPr/W2QK7piRc8Ak4rKxqFUKiwGZEjHYlwyiik6O8qQOfUYgoqsUwJc1KfqWKBLrvhw0LWHaviBC5aoMtHPvuT0ITogO6mIRiKNYQnlGEMtiz1ZPLBX/jicoLbKP4aO2qkcB+MHO0HPBF08g+OGjqzTf+VCNQIfOQG7pJVNPqmM9AIxKPNhR+eZPbSc=
    - secure: ejAPYnLRBBNTD7+2gzDp5ta95akUO40C+gtbBhlxZx3OIUFGcCZcQSY2dGa5JzkT+QBPfXzXddfOy5HrwJ8rXb3x66ADjiE7jtevOXhjKiQ8medGWwy097Yy3DJTEd276Qc8v5pPHrOScXtBz/S1EyLGsVTbpw685aZtb2h4YpsVtNKG7qTR6WOi8okPvbdYmdsbXMIDYzX9CfLOndsSNXVoa9wY1wphjyLmn9zHMBtxRH3zkfwYbKEjAwBhNgAt53y5RinyygReVUDY614Uav4PQwnrvU6CWPTGMQvswCfEZGDFs83Be3FzzrIU9oNjArJx0BOBZvBqlSNUPudnwDsQarppkszXoBroLoqf9hS4tePyJQ+uHvfZ5bnoBGtlwlBC9W3qwRvCbqW0NsP7kZcEntTfXlQoJAPR9LuJ9PdJrFJLcQo5tSsOsh6DBFY8+M4hF8jA7lNdxf8EgtNuAafyxxm9Aks0VtnxLCwAKUSebMgLR3GRV1wrI+VAHQlsOrpqyNyTkAk8EScaiKDxXXMsvcVIb/0IOd8pUC5lp8ugycnPM0zHNtt6t5+17hGvnt12yh+8X2xUz+BE8UPt/70HX1lpM75BOJkr6isdrobmcLQoVk5RNFWqpaMsQLy3IYvnSG/SIYtOUm5AxRtFlJD3lfFDX+9muvpYUuyXiVY=
