name: Check pull request

on:
    pull_request:
        branches:
            - master

jobs:
    # test:
    #     runs-on: ubuntu-20.04
    #     name: Run tests
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2

    #         - name: Setup node
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: 14

    #         - name: Setup Chrome
    #           uses: browser-actions/setup-chrome@latest
    #           with:
    #               chrome-version: stable

    #         - name: Set test variables
    #           run: export CHROME_BIN=$(which chrome)

    #         - name: Install dependencies
    #           run: npm install

    #         - name: Run test
    #           uses: GabrielBB/xvfb-action@v1
    #           with:
    #               run: npm test

    test-all:
        runs-on: ubuntu-20.04
        name: Run tests
        strategy:
            matrix:
                browser: [BrowserStack_Edge, Chrome, Firefox]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Setup Chrome
              if: matrix.browser == 'Chrome'
              uses: browser-actions/setup-chrome@latest
              with:
                  chrome-version: stable

            - name: Setup Firefox
              if: matrix.browser == 'Firefox'
              uses: browser-actions/setup-firefox@latest
              with:
                  firefox-version: latest

            - name: Set test variables
              run: |
                  export CHROME_BIN=$(which chrome);
                  export FIREFOX_BIN=$(which firefox);
                  echo BUILD_SLUG='${{ env.GITHUB_REPOSITORY }} ${{ env.GITHUB_SHA }}' >> $GITHUB_ENV;

            - name: Echo env
              run: echo ${{ env.BUILD_SLUG }}
            # - name: Install dependencies
            #   run: npm install

            # - name: Run test
            #   uses: GabrielBB/xvfb-action@v1
            #   env:
            #       BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
            #       BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
            #   with:
            #       run: npm run test:all -- --browser ${{ matrix.browser }}
