name: Check pull request

on:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-20.04
        name: Test
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Setup Chrome
              uses: browser-actions/setup-chrome@v0.0.0
              with:
                  chrome-version: stable

            - name: Install dependencies
              run: npm install

            - name: Run headless test
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: CHROME_BIN=$(which chrome) npm test
